name: valorant_api
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  animations: ^2.0.11
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  hexcolor: ^3.0.1
  http: ^1.2.1
  palette_generator: ^0.3.3+3
  rive: ^0.13.9
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/Valorant.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/Valorant.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
    - assets/Icons/
